### ISSUE TITLE
Publish initial version of the extension

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/podman-desktop-image-checker-openshift-ext#21]

**Comment by feloy** [comment]
- do we want to download the CLI into the user machine, or do we leverage a container image containing the cli?
- is the extension part of the podman desktop distribution, or is it independent?

**Comment by feloy** [comment]
>> * do we want to download the CLI into the user machine, or do we leverage a container image containing the cli?

>   Should be inside the image

- the API provides a `process.exec` command, do we want to use it to execute `podman exec doa`, or do we want to have a specific execInContainer API?

- `doa` will be executing from inside the container, I suspect it won't have access to podman/docker local images on the host system. Is there some known/documented way to make it work?

- after first tests, I cannot make `doa` access images from `quay.io` or `docker.io/library`. Is it a known limitation?
 
>> * is the extension part of the podman desktop distribution, or is it independent?

>   To be confirmed by @slemeur but should be outside (like the Sandbox one)

**Comment by jeffmaury** [comment]
> > > * do we want to download the CLI into the user machine, or do we leverage a container image containing the cli?
> 
> > Should be inside the image
> 
>     * the API provides a `process.exec` command, do we want to use it to execute `podman exec doa`, or do we want to have a specific execInContainer API?
No exec images are packaged as OCI images as bundle format but they are executed as containers, the content of the image is copied into $HOME/.local/share/containers/podman-desktop/plugins/extensionid
> 
>     * `doa` will be executing from inside the container, I suspect it won't have access to podman/docker local images on the host system. Is there some known/documented way to make it work?
See my remark below

> 
>     * after first tests, I cannot make `doa` access images from `quay.io` or `docker.io/library`. Is it a known limitation?
What is the error ? That should not be the case

> 
> 
> > > * is the extension part of the podman desktop distribution, or is it independent?
Independent

> 
> > To be confirmed by @slemeur but should be outside (like the Sandbox one)

**Comment by feloy** [comment]
Where do we want to publish the image?

Do we want to publish it the same way as https://github.com/containers/podman-desktop-extension-minikube, using github actions, and publishing it in Github Registry?

**Comment by feloy** [comment]
Needs to write on CI to publish image

**Comment by feloy** [comment]
Fixed by https://github.com/containers/podman-desktop-catalog/pull/22
